spring:
  datasource:
    url: jdbc:mysql://192.168.216.113:3306/sg_security?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: Zmj001015.
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.216.113
    port: 6379
    timeout: 5000

server:
  servlet:
    context-path: /api
  port: 10086

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl